global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'windows'
    static_configs:
      - targets: "WINDOWS_IP:9182"

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
